version: '3.9'
services:

  nginx:
    build:
      context: ./nginx
    ports:
      - '8000:80'
    volumes:
      - admin_static:/app/static
    networks:
      - admin

  admin_db:
    build:
      context: ./admin_db
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - admin_db_vol:/var/lib/postgresql/data
    networks:
      - admin

  elasticsearch:
    image: elasticsearch:8.0.0
    environment:
      cluster.routing.allocation.disk.threshold_enabled: false
      xpack.security.enabled: false
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1000m -Xmx1000m

volumes:
  admin_db_vol:
  admin_static:


networks:
  admin:
    name: movies_admin_network
